# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HistoryRecords(object):
    def setupUi(self, HistoryRecords):
        HistoryRecords.setObjectName("HistoryRecords")
        HistoryRecords.resize(770, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(HistoryRecords)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(HistoryRecords)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setStyleSheet("color: black;")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.tableWidget = QtWidgets.QTableWidget(HistoryRecords)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setStyleSheet("color: black;")
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.exportButton = QtWidgets.QPushButton(HistoryRecords)
        self.exportButton.setStyleSheet("color: black;")
        self.exportButton.setObjectName("exportButton")
        self.verticalLayout.addWidget(self.exportButton)
        self.returnButton = QtWidgets.QPushButton(HistoryRecords)
        self.returnButton.setStyleSheet("color: black;")
        self.returnButton.setObjectName("returnButton")
        self.verticalLayout.addWidget(self.returnButton)

        self.retranslateUi(HistoryRecords)
        QtCore.QMetaObject.connectSlotsByName(HistoryRecords)

    def retranslateUi(self, HistoryRecords):
        _translate = QtCore.QCoreApplication.translate
        HistoryRecords.setWindowTitle(_translate("HistoryRecords", "洗车历史记录"))
        self.titleLabel.setText(_translate("HistoryRecords", "洗车历史记录"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("HistoryRecords", "记录编号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("HistoryRecords", "车型"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("HistoryRecords", "洗车开始时间"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("HistoryRecords", "洗车结束时间"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("HistoryRecords", "洗车时长"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("HistoryRecords", "洗车费用"))
        self.exportButton.setText(_translate("HistoryRecords", "导出历史记录"))
        self.returnButton.setText(_translate("HistoryRecords", "返回"))
