# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(903, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.systemTitleLabel = QtWidgets.QLabel(LoginWindow)
        self.systemTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        self.systemTitleLabel.setFont(font)
        self.systemTitleLabel.setObjectName("systemTitleLabel")
        self.verticalLayout.addWidget(self.systemTitleLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(LoginWindow)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.usernameLineEdit.setFont(font)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.verticalLayout.addWidget(self.usernameLineEdit)
        self.passwordLineEdit = QtWidgets.QLineEdit(LoginWindow)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.verticalLayout.addWidget(self.passwordLineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginButton = QtWidgets.QPushButton(LoginWindow)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout.addWidget(self.loginButton)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.forgotPasswordButton = QtWidgets.QPushButton(LoginWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.forgotPasswordButton.setFont(font)
        self.forgotPasswordButton.setObjectName("forgotPasswordButton")
        self.horizontalLayout.addWidget(self.forgotPasswordButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.registerButton = QtWidgets.QPushButton(LoginWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.registerButton.setFont(font)
        self.registerButton.setObjectName("registerButton")
        self.verticalLayout.addWidget(self.registerButton)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "登录"))
        self.systemTitleLabel.setText(_translate("LoginWindow", "欢迎访问自助洗车系统"))
        self.usernameLineEdit.setPlaceholderText(_translate("LoginWindow", "请输入用户名"))
        self.passwordLineEdit.setPlaceholderText(_translate("LoginWindow", "请输入密码"))
        self.loginButton.setText(_translate("LoginWindow", "登录"))
        self.forgotPasswordButton.setText(_translate("LoginWindow", "忘记密码"))
        self.registerButton.setText(_translate("LoginWindow", "注册"))
