# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Recpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(903, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setMinimumHeight(30)
        self.titleLabel.setMaximumHeight(30)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.buttonWidget = QtWidgets.QWidget(self.centralwidget)
        self.buttonWidget.setObjectName("buttonWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttonWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.viewHistoryButton = QtWidgets.QPushButton(self.buttonWidget)
        self.viewHistoryButton.setObjectName("viewHistoryButton")
        self.horizontalLayout.addWidget(self.viewHistoryButton)
        self.startWashButton = QtWidgets.QPushButton(self.buttonWidget)
        self.startWashButton.setObjectName("startWashButton")
        self.horizontalLayout.addWidget(self.startWashButton)
        self.stopWashButton = QtWidgets.QPushButton(self.buttonWidget)
        self.stopWashButton.setObjectName("stopWashButton")
        self.horizontalLayout.addWidget(self.stopWashButton)
        self.startMonitoringButton = QtWidgets.QPushButton(self.buttonWidget)
        self.startMonitoringButton.setObjectName("startMonitoringButton")
        self.horizontalLayout.addWidget(self.startMonitoringButton)
        self.stopMonitoringButton = QtWidgets.QPushButton(self.buttonWidget)
        self.stopMonitoringButton.setObjectName("stopMonitoringButton")
        self.horizontalLayout.addWidget(self.stopMonitoringButton)
        self.exitButton = QtWidgets.QPushButton(self.buttonWidget)
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout.addWidget(self.exitButton)
        self.verticalLayout.addWidget(self.buttonWidget)
        self.videoLabel = QtWidgets.QLabel(self.centralwidget)
        self.videoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.videoLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.videoLabel.setMinimumHeight(500)
        self.videoLabel.setMaximumHeight(500)
        self.videoLabel.setObjectName("videoLabel")
        self.verticalLayout.addWidget(self.videoLabel)
        self.timerLabel = QtWidgets.QLabel(self.centralwidget)
        self.timerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timerLabel.setMinimumHeight(30)
        self.timerLabel.setMaximumHeight(30)
        self.timerLabel.setObjectName("timerLabel")
        self.verticalLayout.addWidget(self.timerLabel)
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "自助洗车系统"))
        self.titleLabel.setText(_translate("MainWindow", "自助洗车系统"))
        self.titleLabel.setStyleSheet(_translate("MainWindow", "\n"
"        QLabel {\n"
"            font-size: 20px;\n"
"            font-weight: bold;\n"
"            background-color: rgba(240, 240, 240, 0.5); /* 半透明的浅灰色 */\n"
"            /* 设置一个几乎透明的边框，或者完全移除边框 */\n"
"            border: 1px solid rgba(204, 204, 204, 0.3); /* 50% 透明度的边框 */\n"
"            /* 或者完全移除边框 */\n"
"            /* border: none; */\n"
"            padding: 5px;\n"
"        }\n"
"       "))
        self.viewHistoryButton.setText(_translate("MainWindow", "查看历史洗车记录"))
        self.startWashButton.setText(_translate("MainWindow", "开始洗车"))
        self.stopWashButton.setText(_translate("MainWindow", "结束洗车"))
        self.startMonitoringButton.setText(_translate("MainWindow", "开启监控"))
        self.stopMonitoringButton.setText(_translate("MainWindow", "关闭监控"))
        self.exitButton.setText(_translate("MainWindow", "退出系统"))
        self.videoLabel.setText(_translate("MainWindow", "视频显示区域"))
        self.videoLabel.setStyleSheet(_translate("MainWindow", "\n"
"        QLabel {\n"
"          background-color: #F0F0F0;\n"
"          border: 1px solid #CCCCCC;\n"
"          font-size: 16px;\n"
"        }\n"
"       "))
        self.timerLabel.setText(_translate("MainWindow", "计时：00:00:00"))
        self.timerLabel.setStyleSheet(_translate("MainWindow", "\n"
"        QLabel {\n"
"            font-size: 20px;\n"
"            font-weight: bold;\n"
"            background-color: rgba(240, 240, 240, 0.5); /* 半透明的浅灰色 */\n"
"            /* 设置一个几乎透明的边框，或者完全移除边框 */\n"
"            border: 1px solid rgba(204, 204, 204, 0.3); /* 50% 透明度的边框 */\n"
"            /* 或者完全移除边框 */\n"
"            /* border: none; */\n"
"            padding: 5px;\n"
"        }\n"
"       "))
        self.statusLabel.setText(_translate("MainWindow", "系统状态"))
        self.statusLabel.setStyleSheet(_translate("MainWindow", "\n"
"        QLabel {\n"
"          background-color: #FFFFFF;\n"
"          border-top: 1px solid #CCCCCC;\n"
"          font-size: 16px;\n"
"          padding: 10px;\n"
"        }\n"
"       "))
