# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regisit.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterWindow(object):
    def setupUi(self, RegisterWindow):
        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.resize(400, 350)
        self.verticalLayout = QtWidgets.QVBoxLayout(RegisterWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(RegisterWindow)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.usernameLineEdit = QtWidgets.QLineEdit(RegisterWindow)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.verticalLayout.addWidget(self.usernameLineEdit)
        self.passwordLineEdit = QtWidgets.QLineEdit(RegisterWindow)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.verticalLayout.addWidget(self.passwordLineEdit)
        self.confirmPasswordLineEdit = QtWidgets.QLineEdit(RegisterWindow)
        self.confirmPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmPasswordLineEdit.setObjectName("confirmPasswordLineEdit")
        self.verticalLayout.addWidget(self.confirmPasswordLineEdit)
        self.emailLineEdit = QtWidgets.QLineEdit(RegisterWindow)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.verticalLayout.addWidget(self.emailLineEdit)
        self.registerButton = QtWidgets.QPushButton(RegisterWindow)
        self.registerButton.setObjectName("registerButton")
        self.verticalLayout.addWidget(self.registerButton)
        self.returnButton = QtWidgets.QPushButton(RegisterWindow)
        self.returnButton.setObjectName("returnButton")
        self.verticalLayout.addWidget(self.returnButton)

        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)

    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "注册"))
        self.label.setText(_translate("RegisterWindow", "注册新用户"))
        self.label.setStyleSheet(_translate("RegisterWindow", "\n"
"        QLabel {\n"
"          font-size: 24px;\n"
"          font-weight: bold;\n"
"          padding: 20px;\n"
"          color: white;\n"
"        }\n"
"       "))
        self.usernameLineEdit.setPlaceholderText(_translate("RegisterWindow", "用户名"))
        self.usernameLineEdit.setStyleSheet(_translate("RegisterWindow", "\n"
"        QLineEdit {\n"
"          padding: 10px;\n"
"          font-size: 16px;\n"
"          border: 1px solid #cccccc;\n"
"          border-radius: 5px;\n"
"        }\n"
"       "))
        self.passwordLineEdit.setPlaceholderText(_translate("RegisterWindow", "密码"))
        self.passwordLineEdit.setStyleSheet(_translate("RegisterWindow", "\n"
"        QLineEdit {\n"
"          padding: 10px;\n"
"          font-size: 16px;\n"
"          border: 1px solid #cccccc;\n"
"          border-radius: 5px;\n"
"        }\n"
"       "))
        self.confirmPasswordLineEdit.setPlaceholderText(_translate("RegisterWindow", "确认密码"))
        self.confirmPasswordLineEdit.setStyleSheet(_translate("RegisterWindow", "\n"
"        QLineEdit {\n"
"          padding: 10px;\n"
"          font-size: 16px;\n"
"          border: 1px solid #cccccc;\n"
"          border-radius: 5px;\n"
"        }\n"
"       "))
        self.emailLineEdit.setPlaceholderText(_translate("RegisterWindow", "邮箱"))
        self.emailLineEdit.setStyleSheet(_translate("RegisterWindow", "\n"
"        QLineEdit {\n"
"          padding: 10px;\n"
"          font-size: 16px;\n"
"          border: 1px solid #cccccc;\n"
"          border-radius: 5px;\n"
"        }\n"
"       "))
        self.registerButton.setText(_translate("RegisterWindow", "注册"))
        self.registerButton.setStyleSheet(_translate("RegisterWindow", "\n"
"        QPushButton {\n"
"          background-color: #007BFF;\n"
"          color: white;\n"
"          padding: 10px;\n"
"          font-size: 16px;\n"
"          border: none;\n"
"          border-radius: 5px;\n"
"        }\n"
"        QPushButton:hover {\n"
"          background-color: #0056b3;\n"
"        }\n"
"        QPushButton:pressed {\n"
"          background-color: #004080;\n"
"        }\n"
"       "))
        self.returnButton.setText(_translate("RegisterWindow", "返回登录"))
        self.returnButton.setStyleSheet(_translate("RegisterWindow", "\n"
"        QPushButton {\n"
"          background-color: #6c757d;\n"
"          color: white;\n"
"          padding: 10px;\n"
"          font-size: 16px;\n"
"          border: none;\n"
"          border-radius: 5px;\n"
"        }\n"
"        QPushButton:hover {\n"
"          background-color: #5a6268;\n"
"        }\n"
"        QPushButton:pressed {\n"
"          background-color: #4e555b;\n"
"        }\n"
"       "))
